// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c6ad617f-6fc5-4554-99b7-19ef3431f852",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_0IkAVqOIv",
    "aws_user_pools_web_client_id": "aas1iinajqhlt6ndinvmu2nhs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://we53nggk6zagljvhn5houbusai.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
